version: "3"

services:
  selenium-hub:
    image: selenium/hub:4.5.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/bin/check-grid.sh" ]
      interval: 10s
      timeout: 30s
      retries: 10
    environment:
      - START_XVFB=false
      # https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html
      # Log Levels: FINEST | FINER | FINE | CONFIG | INFO | WARNING | SEVERE
      - SE_OPTS=--log-level SEVERE

  # chrome:
  #   image: selenium/node-chrome:106.0
  #   shm_size: 2gb
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:105.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      # https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html
      # Log Levels: FINEST | FINER | FINE | CONFIG | INFO | WARNING | SEVERE
      - SE_OPTS=--log-level SEVERE
    deploy:
      replicas: 2

  e2e:
    container_name: e2e
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /dev/shm:/dev/shm
      - ./screenshots:/e2e/screenshots
      - ./config:/e2e/config
      - ./tests:/e2e/tests
      - ./reports:/e2e/reports
      - ./allure-results:/e2e/allure-results
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - HUB_HOST=selenium-hub
    entrypoint: [ "npm", "test" ]
