# https://github.com/actions
name: Run WebdriverIO tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test -- --spec=./tests/av_prod.spec.js
      - uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            reports/*.xml
            allure-results/*.xml
            allure-results/*.png
